services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always

  backend:
    image: jashwanth112002/backend:latest
    container_name: backend_app
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/ddcrud
    depends_on:
      - mongo

  frontend:
    image: jashwanth112002/frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
